file = open("bilgiler.txt","a",encoding="utf-8")
a = input("İsim giriniz")
isima = "isim:"+a
b = input("soyisim giriniz")
isimb = "soyisim:"+b
c = int(input("Yaşınızı giriniz"))
yasc = "yaş:"+ str(c)
d = int(input("telefon numaranızı giriniz"))
teld = "Telefon numarası:"+ str(d)
file.write("-------------\n")
file.write(isima)
file.write("\n")
file.write(isimb)
file.write("\n")
file.write(yasc)
file.write("\n")
file.write(teld)
file.write("\n")
file.write("--------------")
file.close()